; PlatformIO project for BMW G-Chassis BDC / ZGM bench emulator
; Target: ESP32 + TWAI (CAN1) + MCP2515 (CAN2) + LIN UART + LAN8720A (DoIP)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Ethernet (LAN8720A) + FreeRTOS are part of ESP-IDF Arduino core
lib_deps =
  autowp/autowp-mcp2515@^1.3.1

build_unflags =
  -std=gnu++11
  -std=gnu++14

build_flags =
  -DCORE_DEBUG_LEVEL=1
  -std=gnu++17
  -Wno-missing-field-initializers
  ; Uncomment if your LAN8720A board uses a specific PHY address / clock
  ; -DETH_PHY_ADDR=1
  ; -DETH_CLK_MODE=ETH_CLOCK_GPIO0_IN

board_build.partitions = default.csv
